### ISSUE TITLE
How to configure?

### ISSUE THREAD

**Issue by Vistaus** [ilgarmehmetali/budgie-weather-applet#1]
Thank you so, so much for creating a weather applet for Budgie! You rock! :-)
However, I don't see any way to configure it. There's no popover and there are no settings available in Budgie Desktop Settings. Is this a fault on my side or is it because the applet is so new that you didn't implement settings yet? :P

**Comment by Vistaus** [comment]
Oh wait, never mind. Restarting Budgie Desktop Settings makes the settings appear. Sorry, my bad! :( But I don't see any place where I can insert my API key.

**Comment by ilgarmehmetali** [comment]
I wonder why the applet appeared in raven but not its settings?
Just restarting budgie-panel should have made both appear at the same time. 

The text entry bellow the "OpenWeatherMap Api Key" label and "Get Api Key" button is for the apikey. Maybe its not too clear.
![image](https://user-images.githubusercontent.com/889707/28312550-32fd8b2e-6bbc-11e7-8d47-05e523f5ebd6.png)

**Comment by Vistaus** [comment]
The settings are showing up now, but not the API key text box. I'm using Budgie Desktop Settings, which is about to replace Raven anyway.

Edit: oh wait, I do see the text box now. I think it's an Adapta issue that the text box is nearly invisible. Will report there. Thanks for your reply, btw! :)
