### ISSUE TITLE
Adjust Celsius

### ISSUE THREAD

**Issue by Vistaus** [ilgarmehmetali/budgie-weather-applet#2]
So now that I've got the applet to work, I notice that it currently shows 26.68 C. It'd be nice to just see "26.6" there rather than "26.68".

**Comment by ilgarmehmetali** [comment]
fixed at 28df70e32abe93d5e63f28dc8d2a89f6cd9ed07e

**Comment by Vistaus** [comment]
Thanks for fixing this! 😸
